vectara:
  corpus_id: 163
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: docusaurus

docusaurus_crawler:
  docs_repo: "https://github.com/hwchase17/langchain/"
  docs_path: "docs/"
  docs_homepage: "https://docs.langchain.com/docs/"
