vectara:
  corpus_id: 1
  customer_id: 2081868821
  reindex: true
  
crawling:
  crawler_type: docusaurus

docusaurus_crawler:
  base_urls: ["https://azureml-v2.readthedocs.io/en/stable/overview/installation.html"]
  url_regex: [".*vectara.com/docs.*"]
  extensions_to_ignore: ["php", "java", "py", "js"]

