vectara:
  corpus_id: 4
  customer_id: 208857395
  reindex: false

crawling:
  crawler_type: rss

rss_crawler:
  source: pg
  rss_pages: ["http://www.aaronsw.com/2002/feeds/pgessays.rss"]
  days_past: 365
  delay: 1
  extraction: playwright # pdf or playwright
