vectara:
  corpus_id: 141
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: [https://vectara.com]
  delay: 1
  pages_source: sitemap # options are: (1) 'sitemap' automatically retreived from website (2) 'crawl' for recursive crawling
  url_regex: ".*" # regex string or None; ".*" would match any string.
  extraction: playwright # pdf or html
