vectara:
  corpus_id: 140
  customer_id: 1526022105

crawling:
  crawler_type: docusaurus

docusaurus_crawler:
  docs_repo: "https://github.com/vectara/vectara-docs"
  docs_homepage: "https://docs.vectara.com/docs"
