vectara:
  corpus_id: 141
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: [https://vectara.com]
  delay: 1
  pages_source: sitemap # options are: (1) 'sitemap' automatically retreived from website (2) 'crawl' for recursive crawling
  force_prefix: true # if true, ensures base_url is always a strict prefix for crawled URLs
  extraction: playwright # pdf or html
